version: '3'

#env_file:
#  - ./.env

networks:
    frontend:
    backend:

services:
    httpd:
        build: ./build/
        #tty: true
        ports:
            - ${HOST_APACHE_PORT}:80
        volumes:
            - ${APP_PATH}:${DOCKER_APP_PATH}:rw
            - ./etc/apache2/sites-enabled/project.conf:/etc/apache2/sites-enabled/project.conf
        #depends_on:
        #    - app
        networks:
            - frontend
            - backend
